name: animated_progress_example
description: Example app for animated_progress
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_progress:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
