name: animated_progress
description: A beautifully animated progress library for Flutter — smooth linear & circular progress bars with gradients, spinning, value transitions, and programmatic control.
version: 1.0.2
homepage: https://github.com/edris-mazhari/animated_progress/

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
